name: Node Continuous Deployment

on:
  workflow_run:
    workflows: ["Node Continuous Integration"]
    branches: [ main ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@main
      - name: Build and push image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: christiancantarino/maxsum
          registry: docker.io
          tag: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}